name: MasterCI
on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build with dotnet
      run: dotnet build FuSEx.Option/FuSEx.Option.csproj --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack nuget package
        run: dotnet pack FuSEx.Option/FuSEx.Option.csproj --configuration Release

      - name: Push nuget package
        run: dotnet nuget push **/*.nupkg -p:PackageVersion=
          --api-key ${{ secrets.Nuget_Deploy_Key }} 
          --source https://api.nuget.org/v3/index.json